# Generated by Django 5.2.6 on 2026-02-04 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor_name", models.CharField(max_length=100)),
                ("specialty", models.CharField(max_length=100)),
                ("visit_date", models.DateField()),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("checkup", "Annual Checkup"),
                            ("follow_up", "Follow-up"),
                            ("urgent", "Urgent Care"),
                            ("specialist", "Specialist Referral"),
                            ("preventive", "Preventive Care"),
                        ],
                        default="checkup",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("vitals_bp", models.CharField(blank=True, max_length=20)),
                ("vitals_heart_rate", models.IntegerField(blank=True, null=True)),
                (
                    "vitals_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "vitals_weight",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("test_category", models.CharField(max_length=100)),
                ("ordered_by", models.CharField(max_length=100)),
                ("order_date", models.DateField()),
                ("result_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_value", models.CharField(blank=True, max_length=100)),
                ("reference_range", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("is_abnormal", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
    ]
